service: remotion-serverless

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
